packages:
  - "packages/*"

catalog:
  "@alloy-js/babel-preset": "^0.1.1"
  "@alloy-js/core": "^0.3.0"
  "@alloy-js/prettier-plugin-alloy": "^0.1.0"
  "@alloy-js/typescript": "^0.3.0"
  "@babel/cli": "^7.24.8"
  "@babel/core": "^7.24.9"
  "@babel/preset-typescript": "7.26.0"
  "@readme/openapi-parser": "^2.6.0"
  "@types/node": "^22.10.1"
  "@typespec/compiler": "^0.62.0"
  "@typespec/http": "^0.62.0"
  "@typespec/json-schema": "^0.62.0"
  "@typespec/openapi": "^0.62.0"
  "@typespec/openapi3": "^0.62.0"
  "@typespec/rest": "^0.62.0"
  "@typespec/streams": "^0.62.0"
  "@rollup/plugin-babel": "^6.0.4"
  "change-case": "^5.4.4"
  "concurrently": "^8.2.2"
  "prettier": "^3.4.2"
  "rimraf": "6.0.1"
  "typescript": "5.6.3"
  "vitest": "^2.1.8"
  "yaml": "^2.6.1"
