import { createPackage } from "../create-package.js";

export const http = createPackage({
  name: "@typespec/http",
  version: "0.63.0",
  descriptor: {
    ".": {
      Http: [
        "@body",
        "@bodyIgnore",
        "@bodyRoot",
        "@cookie",
        "@delete",
        "@get",
        "@head",
        "@header",
        "@includeInapplicableMetadataInPayload",
        "@multipartBody",
        "@patch",
        "@path",
        "@post",
        "@put",
        "@query",
        "@route",
        "@server",
        "@sharedRoute",
        "@statusCode",
        "@useAuth",
        "AcceptedResponse",
        "ApiKeyAuth",
        "ApiKeyLocation",
        "AuthType",
        "AuthorizationCodeFlow",
        "BadRequestResponse",
        "BasicAuth",
        "BearerAuth",
        "Body",
        "ClientCredentialsFlow",
        "ConflictResponse",
        "CookieOptions",
        "CreatedResponse",
        "File",
        "ForbiddenResponse",
        "HeaderOptions",
        "HttpPart",
        "HttpPartOptions",
        "ImplicitFlow",
        "Link",
        "LinkHeader",
        "LocationHeader",
        "MovedResponse",
        "NoAuth",
        "NoContentResponse",
        "NotFoundResponse",
        "NotModifiedResponse",
        "OAuth2Auth",
        "OAuth2FlowType",
        "OkResponse",
        "OpenIdConnectAuth",
        "PasswordFlow",
        "PathOptions",
        "PlainData",
        "QueryOptions",
        "Response",
        "UnauthorizedResponse",
      ],
    },
    "./streams": {
      "Http.Streams": ["HttpStream", "JsonlStream"],
    },
  },
});
